export const SELL_MY_PROPERTY = 'SELL_MY_PROPERTY'
export const RENT_MY_PROPERTY = 'RENT_MY_PROPERTY'
export const PARTNERSHIPS = 'PARTNERSHIPS'
export const OTHERS = 'OTHERS'
export enum CONTACT_US_TYPES_VALID_VALUES { 'SELL_MY_PROPERTY', 'RENT_MY_PROPERTY', 'PARTNERSHIPS', 'OTHERS' }
