export const APARTMENT = 'APARTMENT'
export const PRIVATE_HOUSE = 'PRIVATE_HOUSE'
export const HOUSE_IN_CONDOMINIUM = 'HOUSE_IN_CONDOMINIUM'
export const RELEASE = 'RELEASE'
export const PROPERTY_VALID_TYPES = [APARTMENT, PRIVATE_HOUSE, HOUSE_IN_CONDOMINIUM, RELEASE]
